spring:
  datasource:
    jdbc-url: jdbc:h2:~/conference-room-booking
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    locations: classpath:/db/migration

charges-per-hour: 100